on: 
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

  DeployStag:
    name: 🎉 Deploy on Staging Server
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'https://staging.tecmetis.com'
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_METIS_SERVER }}
          username: ${{ secrets.FTP_METIS_USERNAME }}
          password: ${{ secrets.FTP_METIS_PASSWORD }}
          server-dir: ${{ secrets.FTP_METIS_STAGING_ENV_PATH }}
        
  DeployDev:
    name: 🎉 Deploy on Development Server
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://dev.tecmetis.com'
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_METIS_SERVER }}
        username: ${{ secrets.FTP_METIS_USERNAME }}
        password: ${{ secrets.FTP_METIS_PASSWORD }}
        server-dir: ${{ secrets.FTP_METIS_DEV_ENV_PATH }}
        
  DeployProd:
    name: 🎉 Deploy on Production Server
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'https://tecmetis.com'
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_METIS_SERVER }}
        username: ${{ secrets.FTP_METIS_USERNAME }}
        password: ${{ secrets.FTP_METIS_PASSWORD }}
        server-dir: ${{ secrets.FTP_METIS_PROD_ENV_PATH }}
        
